export const colors = {
  primary: '#6366f1',
  primaryDark: '#4f46e5',
  primaryLight: '#e0e7ff',
  success: '#10b981',
  successLight: '#d1fae5',
  danger: '#ef4444',
  dangerLight: '#fee2e2',
  warning: '#f59e0b',
  warningLight: '#fef3c7',
  gray50: '#f9fafb',
  gray100: '#f3f4f6',
  gray200: '#e5e7eb',
  gray300: '#d1d5db',
  gray400: '#9ca3af',
  gray500: '#6b7280',
  gray600: '#4b5563',
  gray700: '#374151',
  gray800: '#1f2937',
  gray900: '#111827',
  white: '#ffffff',
};

export const shadows = {
  sm: '0 1px 2px rgba(0,0,0,0.05)',
  md: '0 4px 6px -1px rgba(0,0,0,0.07), 0 2px 4px -1px rgba(0,0,0,0.04)',
  lg: '0 10px 15px -3px rgba(0,0,0,0.08), 0 4px 6px -2px rgba(0,0,0,0.04)',
  xl: '0 20px 25px -5px rgba(0,0,0,0.08)',
};

export const radius = {
  sm: '6px',
  md: '10px',
  lg: '14px',
  xl: '20px',
  full: '9999px',
};

export const T = {
  page: { padding: '28px 32px', background: colors.gray50, minHeight: '100vh', fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif' },
  card: { background: colors.white, borderRadius: radius.lg, padding: '24px', marginBottom: '20px', boxShadow: shadows.md, border: '1px solid ' + colors.gray200 },
  cardTitle: { fontSize: '16px', fontWeight: '700', color: colors.gray800, margin: 0 },
  header: { display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '28px' },
  btnBack: { padding: '8px 16px', background: colors.white, border: '1px solid ' + colors.gray200, borderRadius: radius.md, cursor: 'pointer', fontSize: '13px', fontWeight: '500', color: colors.gray600, display: 'flex', alignItems: 'center', gap: '6px', boxShadow: shadows.sm },
  title: { fontSize: '22px', fontWeight: '800', color: colors.gray900, flex: 1 },
  searchInput: { padding: '9px 14px 9px 36px', border: '1px solid ' + colors.gray200, borderRadius: radius.md, fontSize: '13px', width: '220px', background: colors.white, boxShadow: shadows.sm, outline: 'none' },
  btnPrimary: { padding: '9px 18px', background: colors.primary, color: colors.white, border: 'none', borderRadius: radius.md, cursor: 'pointer', fontWeight: '600', fontSize: '13px', boxShadow: '0 1px 2px rgba(99,102,241,0.3)', display: 'flex', alignItems: 'center', gap: '6px' },
  btnSuccess: { padding: '9px 18px', background: colors.success, color: colors.white, border: 'none', borderRadius: radius.md, cursor: 'pointer', fontWeight: '600', fontSize: '13px' },
  btnDanger: { padding: '9px 18px', background: colors.danger, color: colors.white, border: 'none', borderRadius: radius.md, cursor: 'pointer', fontWeight: '600', fontSize: '13px' },
  btnGhost: { padding: '9px 18px', background: 'transparent', border: '1px solid ' + colors.gray200, borderRadius: radius.md, cursor: 'pointer', fontWeight: '500', fontSize: '13px', color: colors.gray600 },
  table: { width: '100%', borderCollapse: 'collapse', background: colors.white, borderRadius: radius.lg, overflow: 'hidden', boxShadow: shadows.md, border: '1px solid ' + colors.gray200 },
  thead: { background: colors.gray50, borderBottom: '1px solid ' + colors.gray200 },
  th: { padding: '11px 16px', textAlign: 'left', fontSize: '11px', fontWeight: '700', color: colors.gray500, textTransform: 'uppercase', letterSpacing: '0.05em' },
  tr: { borderBottom: '1px solid ' + colors.gray100, transition: 'background 0.1s' },
  td: { padding: '12px 16px', fontSize: '13px', color: colors.gray700 },
  badge: { display: 'inline-flex', alignItems: 'center', padding: '3px 10px', borderRadius: radius.full, fontSize: '11px', fontWeight: '600' },
  badgeSuccess: { background: colors.successLight, color: '#065f46' },
  badgeDanger: { background: colors.dangerLight, color: '#991b1b' },
  badgePrimary: { background: colors.primaryLight, color: colors.primaryDark },
  badgeGray: { background: colors.gray100, color: colors.gray600 },
  overlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, backdropFilter: 'blur(2px)' },
  modal: { background: colors.white, padding: '32px', borderRadius: radius.xl, maxHeight: '85vh', overflowY: 'auto', boxShadow: shadows.xl, border: '1px solid ' + colors.gray200 },
  modalTitle: { fontSize: '18px', fontWeight: '800', color: colors.gray900, marginBottom: '24px' },
  sectionTitle: { fontSize: '11px', fontWeight: '700', color: colors.primary, background: colors.primaryLight, padding: '6px 12px', borderRadius: radius.sm, marginBottom: '16px', marginTop: '12px', textTransform: 'uppercase', letterSpacing: '0.05em' },
  label: { fontSize: '12px', fontWeight: '600', marginBottom: '6px', color: colors.gray600 },
  input: { padding: '9px 12px', border: '1px solid ' + colors.gray200, borderRadius: radius.md, fontSize: '13px', outline: 'none', width: '100%', boxSizing: 'border-box', color: colors.gray800, background: colors.white },
  formGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '8px' },
  formField: { display: 'flex', flexDirection: 'column' },
  formActions: { display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '24px', paddingTop: '20px', borderTop: '1px solid ' + colors.gray100 },
  chip: { padding: '7px 14px', background: colors.white, border: '1px solid ' + colors.gray200, borderRadius: radius.full, cursor: 'pointer', fontSize: '13px', fontWeight: '500', color: colors.gray700, boxShadow: shadows.sm },
  chipActive: { background: colors.primary, color: colors.white, border: '1px solid ' + colors.primary },
  tab: { padding: '9px 16px', background: 'transparent', border: 'none', borderBottom: '2px solid transparent', cursor: 'pointer', fontSize: '13px', fontWeight: '600', color: colors.gray500 },
  tabActive: { color: colors.primary, borderBottom: '2px solid ' + colors.primary },
  rowBetween: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' },
  flexWrap: { display: 'flex', flexWrap: 'wrap', gap: '10px' },
  statCard: { background: colors.white, borderRadius: radius.lg, padding: '20px 24px', boxShadow: shadows.md, border: '1px solid ' + colors.gray200, flex: 1, minWidth: '140px' },
};

export default T;