const express = require('express');
const router = express.Router();
const multer = require('multer');
const { verifierToken } = require('../middleware/auth');
const { importEleves, updateLoraEleves } = require('../controllers/importController');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
router.use(verifierToken);
router.post('/eleves', upload.single('fichier'), importEleves);
router.post('/update-lora', upload.single('fichier'), updateLoraEleves);
module.exports = router;