const express = require('express');
const router = express.Router();
const c = require('../controllers/planningController');
const { verifierToken, autoriser } = require('../middleware/auth');

router.use(verifierToken);
router.get('/creneaux', c.getCreneaux);
router.get('/disponibilites/:prof_id', c.getDisponibilites);
router.get('/disponibilites/:prof_id/remarque', c.getRemarqueDisponibilites);
router.post('/disponibilites/:prof_id', c.saveDisponibilites);
router.post('/disponibilites/:prof_id/remarque', autoriser('admin'), c.saveRemarqueDisponibilites);
router.get('/pools', c.getPools);
router.post('/pools', autoriser('admin'), c.createPool);
router.put('/pools/:id', autoriser('admin'), c.updatePool);
router.delete('/pools/:id', autoriser('admin'), c.deletePool);
router.get('/classe-horaires', c.getAllClasseHoraires);
router.get('/classe-horaires/:classe_id', c.getClasseHoraires);
router.post('/classe-horaires/:classe_id', c.saveClasseHoraires);
router.get('/classe-couleurs', c.getClasseCouleurs);
router.post('/classe-couleurs', autoriser('admin'), c.saveClasseCouleur);
router.get('/prof-couleurs', c.getProfCouleurs);
router.post('/prof-couleurs', autoriser('admin'), c.saveProfCouleur);
router.get('/branche-couleurs', c.getBrancheCouleurs);
router.post('/branche-couleurs', autoriser('admin'), c.saveBrancheCouleur);
router.get('/affectations', c.getAffectations);
router.post('/affectations', autoriser('admin'), c.saveAffectation);
router.delete('/affectations/:id', autoriser('admin'), c.deleteAffectation);
router.post('/titulaires', autoriser('admin'), c.saveClasseTitulaire);
router.get('/planning-branches', c.getPlanningBranches);
router.post('/planning-branches', autoriser('admin'), c.savePlanningBranche);
router.delete('/planning-branches', autoriser('admin'), c.deletePlanningBranche);
router.get('/general', c.getPlanningGeneral);
router.get('/prof/:prof_id', c.getPlanningProf);
router.get('/classe/:classe_id', c.getPlanningClasse);

module.exports = router;